kind: pipeline
type: docker
name: android-ci

steps:
  - name: build-android
    image: ghcr.io/cirruslabs/android-sdk:34
    environment:
      ANDROID_HOME: /opt/android-sdk-linux
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
