kind: pipeline
type: docker
name: android-ci

steps:
  - name: build-android
    image: ghcr.io/cirruslabs/android-sdk:34
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug

  - name: upload-apk
    image: alpine
    commands:
      - mkdir -p artifacts
      - cp app/build/outputs/apk/debug/app-debug.apk artifacts/
    when:
      status:
        - success

artifacts:
  paths:
    - artifacts/*.apk
