kind: pipeline
type: docker
name: android-ci

steps:
  - name: build-android
    image: mobiledevops/android-sdk-image:34
    environment:
      GRADLE_USER_HOME: /drone/src/.gradle
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
